version: '2.0'

services:
  node-api:
    build:
      context: .
    # Expose ports [HOST:CONTAINER}
    ports:
      - "28080:28080"
    # Set environment variables from this file
    # Overwrite any env var defined in .env file (if required)
    environment:
      - MONGO_HOST=mongodb://mongo/node-api
    links:
      - mongo:mongo
  mongo:
    image: "mongo:3.4.4"
    ports:
      - "27017:27017"
